### ISSUE TITLE
Add support for setting/getting the RTC

### ISSUE THREAD

**Issue by dhylands** [mozilla-sensorweb/sensorweb-firmware#35]
We need a function which gets/sets the RTC. From a security standpoint, it makes sense to retrieve the time from the server.

I think that using the linux epoch (Jan 1, 1970) in UTC timezone makes the most sense.

**Comment by fabricedesre** [comment]
I filed https://github.com/mozilla-sensorweb/sensorweb-server/issues/29 on the server side.

**Comment by dhylands** [comment]
Fixed by: https://github.com/fabricedesre/cc3200-rs/commit/166dca5290aaa7e49842e82447cb2afcf917a0e5
