### ISSUE TITLE
Implement an ISO date formatter.

### ISSUE THREAD

**Issue by fabricedesre** [mozilla-sensorweb/sensorweb-firmware#41]
We need to send ISO dates to the SensorThings API (see https://github.com/mozilla-sensorweb/sensorthings/blob/master/doc/usage.md#request-5), and not just seconds since epoch.

**Comment by dhylands** [comment]
Fixed by https://github.com/fabricedesre/cc3200-rs/commit/a67f02eda32b6f5745aa35c30ebd3ff1657d7fbc
